import heroImage from "../assets/hero.png";
import type { NodeId, SceneGraph, SceneNode } from "../types/scene";
import { generateId } from "./id";

const sectionId = generateId();
const sectionTitleId = generateId();
const sectionBadgeId = generateId();
const cardFrameId = generateId();
const cardAvatarId = generateId();
const cardNameId = generateId();
const rectId = generateId();
const ringId = generateId();
const lineId = generateId();
const arrowId = generateId();
const pathId = generateId();
const imageId = generateId();

const nodes: Record<NodeId, SceneNode> = {
  [sectionId]: {
    id: sectionId,
    type: "section",
    name: "Header",
    parentId: null,
    x: 40,
    y: 40,
    width: 1120,
    height: 100,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    label: "Header",
    children: [sectionTitleId, sectionBadgeId],
  },
  [sectionTitleId]: {
    id: sectionTitleId,
    type: "text",
    name: "Title",
    parentId: sectionId,
    x: 0,
    y: 0,
    width: 300,
    height: 36,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    content: "Open Canvas",
    fontSize: 28,
    fontFamily: "sans-serif",
    fontWeight: 700,
    color: "#111827",
    align: "left",
  },
  [sectionBadgeId]: {
    id: sectionBadgeId,
    type: "rect",
    name: "Badge",
    parentId: sectionId,
    x: 1000,
    y: 10,
    width: 80,
    height: 32,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    fill: "#4f46e5",
    stroke: null,
    strokeWidth: 0,
    cornerRadius: 16,
  },
  [cardFrameId]: {
    id: cardFrameId,
    type: "frame",
    name: "Card",
    parentId: null,
    x: 40,
    y: 180,
    width: 320,
    height: 200,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    fill: "#f5f5f5",
    clipsContent: true,
    cornerRadius: 16,
    children: [cardAvatarId, cardNameId],
  },
  [cardAvatarId]: {
    id: cardAvatarId,
    type: "ellipse",
    name: "Avatar",
    parentId: cardFrameId,
    x: 20,
    y: 20,
    width: 64,
    height: 64,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    fill: "#fbbf24",
    stroke: null,
    strokeWidth: 0,
  },
  [cardNameId]: {
    id: cardNameId,
    type: "text",
    name: "Name",
    parentId: cardFrameId,
    x: 100,
    y: 40,
    width: 180,
    height: 24,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    content: "Jane Doe",
    fontSize: 18,
    fontFamily: "sans-serif",
    fontWeight: 500,
    color: "#1f2937",
    align: "left",
  },
  [rectId]: {
    id: rectId,
    type: "rect",
    name: "Rotated Rect",
    parentId: null,
    x: 420,
    y: 180,
    width: 200,
    height: 120,
    rotation: 6,
    opacity: 1,
    visible: true,
    locked: false,
    fill: "#22c55e",
    stroke: "#166534",
    strokeWidth: 2,
    cornerRadius: 8,
  },
  [ringId]: {
    id: ringId,
    type: "ellipse",
    name: "Ring",
    parentId: null,
    x: 680,
    y: 180,
    width: 140,
    height: 140,
    rotation: 0,
    opacity: 0.8,
    visible: true,
    locked: false,
    fill: null,
    stroke: "#0ea5e9",
    strokeWidth: 4,
  },
  [lineId]: {
    id: lineId,
    type: "line",
    name: "Line",
    parentId: null,
    x: 420,
    y: 340,
    x2: 620,
    y2: 340,
    width: 200,
    height: 0,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    stroke: "#111827",
    strokeWidth: 2,
  },
  [arrowId]: {
    id: arrowId,
    type: "arrow",
    name: "Arrow",
    parentId: null,
    x: 420,
    y: 380,
    x2: 620,
    y2: 420,
    width: 200,
    height: 40,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    stroke: "#111827",
    strokeWidth: 2,
    arrowheadSize: 10,
  },
  [pathId]: {
    id: pathId,
    type: "path",
    name: "Triangle",
    parentId: null,
    x: 680,
    y: 340,
    width: 100,
    height: 80,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    closed: true,
    fill: "#f472b6",
    stroke: null,
    strokeWidth: 0,
    points: [
      { x: 0, y: 0 },
      { x: 100, y: 0 },
      { x: 50, y: 80 },
    ],
  },
  [imageId]: {
    id: imageId,
    type: "image",
    name: "Hero",
    parentId: null,
    x: 860,
    y: 180,
    width: 180,
    height: 140,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    src: heroImage,
    objectFit: "cover",
  },
};

export const seedScene: SceneGraph = {
  nodes,
  rootIds: [sectionId, cardFrameId, rectId, ringId, lineId, arrowId, pathId, imageId],
};
