import massageImage from "../assets/massage.jpeg";
import type { NodeId, SceneGraph, SceneNode } from "../types/scene";
import { generateId } from "./id";

// A realistic hero section — one "Desktop" frame preset (1440x1024) sized
// composition, rather than a grab-bag of every shape type. Everything but
// the image frame lives at the frame's own origin (0,0), so each child's
// local x/y already reads as its position within the frame with no mental
// offset — the one deliberate simplification that makes the coordinates
// below easy to follow.
const heroFrameId = generateId();
const navLogoId = generateId();
const navLinksGroupId = generateId();
const navLinkServicesId = generateId();
const navLinkAboutId = generateId();
const navLinkContactId = generateId();
const navButtonGroupId = generateId();
const navButtonRectId = generateId();
const navButtonTextId = generateId();
const eyebrowId = generateId();
const headlineId = generateId();
const subheadId = generateId();
const ctaGroupId = generateId();
const ctaRectId = generateId();
const ctaTextId = generateId();
const imageFrameId = generateId();
const imageId = generateId();

// Warm, spa-brand palette pulled from the hero photo itself (cream
// background, deep sage accent) rather than the app's own UI tokens —
// scene content and app chrome are deliberately unrelated color systems.
const CREAM = "#F7F1E8";
const CHARCOAL = "#1E2A24";
const SAGE = "#2F5D46";
const MUTED = "#5B6B63";

const nodes: Record<NodeId, SceneNode> = {
  [heroFrameId]: {
    id: heroFrameId,
    type: "frame",
    name: "Hero Section",
    parentId: null,
    x: 0,
    y: 0,
    width: 1440,
    height: 1024,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    fill: CREAM,
    clipsContent: true,
    cornerRadius: 0,
    children: [navLogoId, navLinksGroupId, navButtonGroupId, eyebrowId, headlineId, subheadId, ctaGroupId, imageFrameId],
  },
  [navLogoId]: {
    id: navLogoId,
    type: "text",
    name: "Logo",
    parentId: heroFrameId,
    x: 64,
    y: 40,
    width: 220,
    height: 30,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    content: "Serene",
    fontSize: 24,
    fontFamily: "Georgia",
    fontWeight: 700,
    fontStyle: "normal",
    letterSpacing: 0.5,
    lineHeight: 1.2,
    textDecoration: "none",
    color: CHARCOAL,
    align: "left",
  },
  [navLinksGroupId]: {
    id: navLinksGroupId,
    type: "group",
    name: "Nav Links",
    parentId: heroFrameId,
    x: 600,
    y: 46,
    width: 236,
    height: 18,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    children: [navLinkServicesId, navLinkAboutId, navLinkContactId],
  },
  [navLinkServicesId]: {
    id: navLinkServicesId,
    type: "text",
    name: "Services",
    parentId: navLinksGroupId,
    x: 0,
    y: 0,
    width: 64,
    height: 18,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    content: "Services",
    fontSize: 14,
    fontFamily: "sans-serif",
    fontWeight: 500,
    fontStyle: "normal",
    letterSpacing: 0.2,
    lineHeight: 1.2,
    textDecoration: "none",
    color: MUTED,
    align: "left",
  },
  [navLinkAboutId]: {
    id: navLinkAboutId,
    type: "text",
    name: "About",
    parentId: navLinksGroupId,
    x: 96,
    y: 0,
    width: 48,
    height: 18,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    content: "About",
    fontSize: 14,
    fontFamily: "sans-serif",
    fontWeight: 500,
    fontStyle: "normal",
    letterSpacing: 0.2,
    lineHeight: 1.2,
    textDecoration: "none",
    color: MUTED,
    align: "left",
  },
  [navLinkContactId]: {
    id: navLinkContactId,
    type: "text",
    name: "Contact",
    parentId: navLinksGroupId,
    x: 176,
    y: 0,
    width: 60,
    height: 18,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    content: "Contact",
    fontSize: 14,
    fontFamily: "sans-serif",
    fontWeight: 500,
    fontStyle: "normal",
    letterSpacing: 0.2,
    lineHeight: 1.2,
    textDecoration: "none",
    color: MUTED,
    align: "left",
  },
  [navButtonGroupId]: {
    id: navButtonGroupId,
    type: "group",
    name: "Nav CTA",
    parentId: heroFrameId,
    x: 1246,
    y: 28,
    width: 130,
    height: 44,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    children: [navButtonRectId, navButtonTextId],
  },
  [navButtonRectId]: {
    id: navButtonRectId,
    type: "rect",
    name: "Background",
    parentId: navButtonGroupId,
    x: 0,
    y: 0,
    width: 130,
    height: 44,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    fill: SAGE,
    stroke: null,
    strokeWidth: 0,
    cornerRadius: 8,
  },
  [navButtonTextId]: {
    id: navButtonTextId,
    type: "text",
    name: "Label",
    parentId: navButtonGroupId,
    x: 0,
    y: 15,
    width: 130,
    height: 17,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    content: "Book Now",
    fontSize: 14,
    fontFamily: "sans-serif",
    fontWeight: 600,
    fontStyle: "normal",
    letterSpacing: 0.3,
    lineHeight: 1,
    textDecoration: "none",
    color: "#FFFFFF",
    align: "center",
  },
  [eyebrowId]: {
    id: eyebrowId,
    type: "text",
    name: "Eyebrow",
    parentId: heroFrameId,
    x: 64,
    y: 272,
    width: 400,
    height: 18,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    content: "WELLNESS & THERAPY",
    fontSize: 13,
    fontFamily: "sans-serif",
    fontWeight: 700,
    fontStyle: "normal",
    letterSpacing: 2,
    lineHeight: 1.2,
    textDecoration: "none",
    color: SAGE,
    align: "left",
  },
  [headlineId]: {
    id: headlineId,
    type: "text",
    name: "Headline",
    parentId: heroFrameId,
    x: 64,
    y: 300,
    width: 560,
    height: 150,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    content: "Relax your body.\nRenew your mind.",
    fontSize: 56,
    fontFamily: "Georgia",
    fontWeight: 700,
    fontStyle: "normal",
    letterSpacing: 0,
    lineHeight: 1.15,
    textDecoration: "none",
    color: CHARCOAL,
    align: "left",
  },
  [subheadId]: {
    id: subheadId,
    type: "text",
    name: "Subheading",
    parentId: heroFrameId,
    x: 64,
    y: 460,
    width: 460,
    height: 90,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    content: "Book a session with our licensed therapists and feel the difference after just one visit.",
    fontSize: 18,
    fontFamily: "sans-serif",
    fontWeight: 400,
    fontStyle: "normal",
    letterSpacing: 0,
    lineHeight: 1.6,
    textDecoration: "none",
    color: MUTED,
    align: "left",
  },
  [ctaGroupId]: {
    id: ctaGroupId,
    type: "group",
    name: "CTA Button",
    parentId: heroFrameId,
    x: 64,
    y: 560,
    width: 220,
    height: 56,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    children: [ctaRectId, ctaTextId],
  },
  [ctaRectId]: {
    id: ctaRectId,
    type: "rect",
    name: "Background",
    parentId: ctaGroupId,
    x: 0,
    y: 0,
    width: 220,
    height: 56,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    fill: SAGE,
    stroke: null,
    strokeWidth: 0,
    cornerRadius: 10,
  },
  [ctaTextId]: {
    id: ctaTextId,
    type: "text",
    name: "Label",
    parentId: ctaGroupId,
    x: 0,
    y: 20,
    width: 220,
    height: 16,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    content: "Book a Session",
    fontSize: 16,
    fontFamily: "sans-serif",
    fontWeight: 600,
    fontStyle: "normal",
    letterSpacing: 0.2,
    lineHeight: 1,
    textDecoration: "none",
    color: "#FFFFFF",
    align: "center",
  },
  [imageFrameId]: {
    id: imageFrameId,
    type: "frame",
    name: "Hero Image",
    parentId: heroFrameId,
    x: 800,
    y: 140,
    width: 576,
    height: 744,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    fill: null,
    clipsContent: true,
    cornerRadius: 28,
    children: [imageId],
  },
  [imageId]: {
    id: imageId,
    type: "image",
    name: "Photo",
    parentId: imageFrameId,
    x: 0,
    y: 0,
    width: 576,
    height: 744,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    src: massageImage,
    objectFit: "cover",
  },
};

export const seedScene: SceneGraph = {
  nodes,
  rootIds: [heroFrameId],
};
