import { generateId } from "@open-canvas/commands";
import massageImage from "../assets/massage.jpeg";
import type { NodeId, SceneGraph, SceneNode } from "@open-canvas/schema";

// A realistic hero section, built with the same auto-layout structure a
// human author would reach for by hand: an outer vertical flex frame
// (Hero Section) stacking a horizontal Nav row and a horizontal Content
// row, with Content's own text column (Copy) itself a nested vertical
// flex frame — hug-sized against its own children. x/y/width/height on
// every flex-managed node below are just placeholders; createSceneStore
// resolves the real values from layoutMode/direction/gap/padding/sizing
// before the very first render (see its own comment on this), so there's
// nothing to hand-compute or keep in sync here.
const heroFrameId = generateId();
const navRowId = generateId();
const navLogoId = generateId();
const navLinksGroupId = generateId();
const navLinkServicesId = generateId();
const navLinkAboutId = generateId();
const navLinkContactId = generateId();
const navButtonGroupId = generateId();
const navButtonRectId = generateId();
const navButtonTextId = generateId();
const contentRowId = generateId();
const copyId = generateId();
const eyebrowId = generateId();
const headlineId = generateId();
const subheadId = generateId();
const ctaGroupId = generateId();
const ctaRectId = generateId();
const ctaTextId = generateId();
const imageFrameId = generateId();
const imageId = generateId();

// Warm, spa-brand palette pulled from the hero photo itself (cream
// background, deep sage accent) rather than the app's own UI tokens —
// scene content and app chrome are deliberately unrelated color systems.
const CREAM = "#F7F1E8";
const CHARCOAL = "#1E2A24";
const SAGE = "#2F5D46";
const MUTED = "#5B6B63";

// Shared by every plain layout-only wrapper frame below (Nav, Content,
// Copy) — none of them have their own fill/stroke, they exist purely to
// group and arrange their children.
const wrapperStyle = {
  fill: null,
  stroke: null,
  strokeWidth: 0,
  strokeStyle: "solid",
  clipsContent: false,
  cornerRadius: 0,
} as const;

const nodes: Record<NodeId, SceneNode> = {
  [heroFrameId]: {
    id: heroFrameId,
    type: "frame",
    name: "Hero Section",
    parentId: null,
    x: 0,
    y: 0,
    width: 1440,
    height: 1024,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    sizingHorizontal: "fixed",
    sizingVertical: "fixed",
    positioning: "flow",
    fill: CREAM,
    stroke: null,
    strokeWidth: 0,
    strokeStyle: "solid",
    clipsContent: true,
    cornerRadius: 0,
    layoutMode: "flex",
    direction: "column",
    gap: 80,
    padding: { top: 40, right: 64, bottom: 64, left: 64 },
    primaryAxisAlign: "start",
    crossAxisAlign: "start",
    children: [navRowId, contentRowId],
  },
  [navRowId]: {
    id: navRowId,
    type: "frame",
    name: "Nav",
    parentId: heroFrameId,
    x: 0,
    y: 0,
    width: 0,
    height: 0,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    sizingHorizontal: "fill",
    sizingVertical: "hug",
    positioning: "flow",
    ...wrapperStyle,
    layoutMode: "flex",
    direction: "row",
    gap: 0,
    padding: { top: 0, right: 0, bottom: 0, left: 0 },
    primaryAxisAlign: "spaceBetween",
    crossAxisAlign: "center",
    children: [navLogoId, navLinksGroupId, navButtonGroupId],
  },
  [navLogoId]: {
    id: navLogoId,
    type: "text",
    name: "Logo",
    parentId: navRowId,
    x: 0,
    y: 0,
    width: 220,
    height: 30,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    sizingHorizontal: "fixed",
    sizingVertical: "fixed",
    positioning: "flow",
    content: "Serene",
    fontSize: 24,
    fontFamily: "Georgia",
    fontWeight: 700,
    fontStyle: "normal",
    letterSpacing: 0.5,
    lineHeight: 1.2,
    textDecoration: "none",
    color: CHARCOAL,
    align: "left",
  },
  [navLinksGroupId]: {
    id: navLinksGroupId,
    type: "group",
    name: "Nav Links",
    parentId: navRowId,
    x: 0,
    y: 0,
    width: 236,
    height: 18,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    sizingHorizontal: "fixed",
    sizingVertical: "fixed",
    positioning: "flow",
    children: [navLinkServicesId, navLinkAboutId, navLinkContactId],
  },
  [navLinkServicesId]: {
    id: navLinkServicesId,
    type: "text",
    name: "Services",
    parentId: navLinksGroupId,
    x: 0,
    y: 0,
    width: 64,
    height: 18,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    sizingHorizontal: "fixed",
    sizingVertical: "fixed",
    positioning: "flow",
    content: "Services",
    fontSize: 14,
    fontFamily: "sans-serif",
    fontWeight: 500,
    fontStyle: "normal",
    letterSpacing: 0.2,
    lineHeight: 1.2,
    textDecoration: "none",
    color: MUTED,
    align: "left",
  },
  [navLinkAboutId]: {
    id: navLinkAboutId,
    type: "text",
    name: "About",
    parentId: navLinksGroupId,
    x: 96,
    y: 0,
    width: 48,
    height: 18,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    sizingHorizontal: "fixed",
    sizingVertical: "fixed",
    positioning: "flow",
    content: "About",
    fontSize: 14,
    fontFamily: "sans-serif",
    fontWeight: 500,
    fontStyle: "normal",
    letterSpacing: 0.2,
    lineHeight: 1.2,
    textDecoration: "none",
    color: MUTED,
    align: "left",
  },
  [navLinkContactId]: {
    id: navLinkContactId,
    type: "text",
    name: "Contact",
    parentId: navLinksGroupId,
    x: 176,
    y: 0,
    width: 60,
    height: 18,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    sizingHorizontal: "fixed",
    sizingVertical: "fixed",
    positioning: "flow",
    content: "Contact",
    fontSize: 14,
    fontFamily: "sans-serif",
    fontWeight: 500,
    fontStyle: "normal",
    letterSpacing: 0.2,
    lineHeight: 1.2,
    textDecoration: "none",
    color: MUTED,
    align: "left",
  },
  [navButtonGroupId]: {
    id: navButtonGroupId,
    type: "group",
    name: "Nav CTA",
    parentId: navRowId,
    x: 0,
    y: 0,
    width: 130,
    height: 44,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    sizingHorizontal: "fixed",
    sizingVertical: "fixed",
    positioning: "flow",
    children: [navButtonRectId, navButtonTextId],
  },
  [navButtonRectId]: {
    id: navButtonRectId,
    type: "rect",
    name: "Background",
    parentId: navButtonGroupId,
    x: 0,
    y: 0,
    width: 130,
    height: 44,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    sizingHorizontal: "fixed",
    sizingVertical: "fixed",
    positioning: "flow",
    fill: SAGE,
    stroke: null,
    strokeWidth: 0,
    strokeStyle: "solid",
    cornerRadius: 8,
  },
  [navButtonTextId]: {
    id: navButtonTextId,
    type: "text",
    name: "Label",
    parentId: navButtonGroupId,
    x: 0,
    y: 15,
    width: 130,
    height: 17,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    sizingHorizontal: "fixed",
    sizingVertical: "fixed",
    positioning: "flow",
    content: "Book Now",
    fontSize: 14,
    fontFamily: "sans-serif",
    fontWeight: 600,
    fontStyle: "normal",
    letterSpacing: 0.3,
    lineHeight: 1,
    textDecoration: "none",
    color: "#FFFFFF",
    align: "center",
  },
  [contentRowId]: {
    id: contentRowId,
    type: "frame",
    name: "Content",
    parentId: heroFrameId,
    x: 0,
    y: 0,
    width: 0,
    height: 0,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    sizingHorizontal: "fill",
    sizingVertical: "hug",
    positioning: "flow",
    ...wrapperStyle,
    layoutMode: "flex",
    direction: "row",
    gap: 64,
    padding: { top: 0, right: 0, bottom: 0, left: 0 },
    primaryAxisAlign: "start",
    crossAxisAlign: "center",
    children: [copyId, imageFrameId],
  },
  [copyId]: {
    id: copyId,
    type: "frame",
    name: "Copy",
    parentId: contentRowId,
    x: 0,
    y: 0,
    width: 0,
    height: 0,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    sizingHorizontal: "hug",
    sizingVertical: "hug",
    positioning: "flow",
    ...wrapperStyle,
    layoutMode: "flex",
    direction: "column",
    gap: 24,
    padding: { top: 0, right: 0, bottom: 0, left: 0 },
    primaryAxisAlign: "start",
    crossAxisAlign: "start",
    children: [eyebrowId, headlineId, subheadId, ctaGroupId],
  },
  [eyebrowId]: {
    id: eyebrowId,
    type: "text",
    name: "Eyebrow",
    parentId: copyId,
    x: 0,
    y: 0,
    width: 400,
    height: 18,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    sizingHorizontal: "fixed",
    sizingVertical: "fixed",
    positioning: "flow",
    content: "WELLNESS & THERAPY",
    fontSize: 13,
    fontFamily: "sans-serif",
    fontWeight: 700,
    fontStyle: "normal",
    letterSpacing: 2,
    lineHeight: 1.2,
    textDecoration: "none",
    color: SAGE,
    align: "left",
  },
  [headlineId]: {
    id: headlineId,
    type: "text",
    name: "Headline",
    parentId: copyId,
    x: 0,
    y: 0,
    width: 560,
    height: 150,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    sizingHorizontal: "fixed",
    sizingVertical: "fixed",
    positioning: "flow",
    content: "Relax your body.\nRenew your mind.",
    fontSize: 56,
    fontFamily: "Georgia",
    fontWeight: 700,
    fontStyle: "normal",
    letterSpacing: 0,
    lineHeight: 1.15,
    textDecoration: "none",
    color: CHARCOAL,
    align: "left",
  },
  [subheadId]: {
    id: subheadId,
    type: "text",
    name: "Subheading",
    parentId: copyId,
    x: 0,
    y: 0,
    width: 460,
    height: 90,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    sizingHorizontal: "fixed",
    sizingVertical: "fixed",
    positioning: "flow",
    content: "Book a session with our licensed therapists and feel the difference after just one visit.",
    fontSize: 18,
    fontFamily: "sans-serif",
    fontWeight: 400,
    fontStyle: "normal",
    letterSpacing: 0,
    lineHeight: 1.6,
    textDecoration: "none",
    color: MUTED,
    align: "left",
  },
  [ctaGroupId]: {
    id: ctaGroupId,
    type: "group",
    name: "CTA Button",
    parentId: copyId,
    x: 0,
    y: 0,
    width: 220,
    height: 56,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    sizingHorizontal: "fixed",
    sizingVertical: "fixed",
    positioning: "flow",
    children: [ctaRectId, ctaTextId],
  },
  [ctaRectId]: {
    id: ctaRectId,
    type: "rect",
    name: "Background",
    parentId: ctaGroupId,
    x: 0,
    y: 0,
    width: 220,
    height: 56,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    sizingHorizontal: "fixed",
    sizingVertical: "fixed",
    positioning: "flow",
    fill: SAGE,
    stroke: null,
    strokeWidth: 0,
    strokeStyle: "solid",
    cornerRadius: 10,
  },
  [ctaTextId]: {
    id: ctaTextId,
    type: "text",
    name: "Label",
    parentId: ctaGroupId,
    x: 0,
    y: 20,
    width: 220,
    height: 16,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    sizingHorizontal: "fixed",
    sizingVertical: "fixed",
    positioning: "flow",
    content: "Book a Session",
    fontSize: 16,
    fontFamily: "sans-serif",
    fontWeight: 600,
    fontStyle: "normal",
    letterSpacing: 0.2,
    lineHeight: 1,
    textDecoration: "none",
    color: "#FFFFFF",
    align: "center",
  },
  [imageFrameId]: {
    id: imageFrameId,
    type: "frame",
    name: "Hero Image",
    parentId: contentRowId,
    x: 0,
    y: 0,
    width: 576,
    height: 744,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    sizingHorizontal: "fixed",
    sizingVertical: "fixed",
    positioning: "flow",
    fill: null,
    stroke: null,
    strokeWidth: 0,
    strokeStyle: "solid",
    clipsContent: true,
    cornerRadius: 28,
    layoutMode: "none",
    direction: "row",
    gap: 0,
    padding: { top: 0, right: 0, bottom: 0, left: 0 },
    primaryAxisAlign: "start",
    crossAxisAlign: "start",
    children: [imageId],
  },
  [imageId]: {
    id: imageId,
    type: "image",
    name: "Photo",
    parentId: imageFrameId,
    x: 0,
    y: 0,
    width: 576,
    height: 744,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    semantics: null,
    interactions: [],
    sizingHorizontal: "fixed",
    sizingVertical: "fixed",
    positioning: "flow",
    src: massageImage,
    objectFit: "cover",
    filters: { blur: 0, brightness: 1, contrast: 1, grayscale: 0, saturate: 1, sepia: 0, hueRotate: 0 },
  },
};

export const seedScene: SceneGraph = {
  nodes,
  rootIds: [heroFrameId],
};
