export interface IconManifestEntry {
  name: string;
  pascalName: string;
  tags: string[];
  viewBox: string;
  d: string;
}

let cached: Promise<IconManifestEntry[]> | null = null;

// The manifest (~800KB of JSON, generated by scripts/generate-icon-manifest.mjs
// — see that file for how it's regenerated) is dynamically imported, not a
// static import, so Vite code-splits it into its own chunk that only loads
// once the Icons tab is actually opened, not on initial page load.
export function loadIconManifest(): Promise<IconManifestEntry[]> {
  cached ??= import("../assets/icons/manifest.json").then(
    (mod) => mod.default as IconManifestEntry[],
  );
  return cached;
}
