services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: open-canvas
    ports:
      - "5432:5432"
    volumes:
      - open-canvas-postgres:/var/lib/postgresql/data

volumes:
  open-canvas-postgres:
